service: event-driven-nestjs
frameworkVersion: '3'

plugins:
  - serverless-ssm-fetch

package:
  exclude:
    - './**'
  include:
    - 'dist/**' # only package the webpack 'dist' folder

custom:
  serverlessSsmFetch:
    SENDGRID_API_KEY: '/${self:provider.stage}/sendgrid/apiKey~true'

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  memorySize: 1024
  timeout: 10
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  emailer:
    handler: dist/main.handler # the output of webpack. requires 'yarn build'
    environment:
      FROM_MAIL_DOMAIN: <YOUR_DOMAIN_HERE>
    events:
      - eventBridge:
          pattern:
            detail-type:
              - payments.InvoicePaid
